name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Check credentials
        id: docker-credentials
        run: |
          echo ::set-output name=defined::$(test -n "${{ secrets.DOCKERHUB_USERNAME }}" && echo true || echo false)
      - name: Docker Login
        if: steps.docker-credentials.outputs.defined == 'true'
        run: |
          username="${{ secrets.DOCKERHUB_USERNAME }}"
          password="${{ secrets.DOCKERHUB_PASSWORD }}"
          echo "$password" | docker login --username "$username" --password-stdin
      - name: Build Docker image
        if: steps.docker-credentials.outputs.defined == 'true'
        run: |
          docker buildx create --name test-builder --use
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t 4km3/test-docker-publication --push .
      # - name: Push Docker image
      #   if: steps.docker-credentials.outputs.defined == 'true'
      #   run: |
      #     docker push 4km3/test-docker-publication
